import { createContext, useContext, useState, ReactNode } from 'react';

export type LangCode = 'en' | 'es' | 'zh' | 'vi' | 'ar' | 'fr';

export const LANGUAGES = [
  { code: 'en' as LangCode, label: 'EN', flag: '🇺🇸', name: 'English' },
  { code: 'es' as LangCode, label: 'ES', flag: '🇲🇽', name: 'Español' },
  { code: 'zh' as LangCode, label: 'ZH', flag: '🇨🇳', name: '中文' },
  { code: 'vi' as LangCode, label: 'VI', flag: '🇻🇳', name: 'Tiếng Việt' },
  { code: 'ar' as LangCode, label: 'AR', flag: '🇸🇦', name: 'العربية' },
  { code: 'fr' as LangCode, label: 'FR', flag: '🇫🇷', name: 'Français' },
];

const UI: Record<LangCode, Record<string, string>> = {
  en: {
    // ── Sidebar nav ───────────────────────────────────────────────
    Dashboard: 'Dashboard', Prepare: 'Prepare', 'Crisis Advisor': 'Crisis Advisor',
    Spending: 'Spending', 'Claim Guard': 'Claim Guard', Settings: 'Settings',
    Main: 'Main', Tools: 'Tools', Account: 'Account', 'Reset Profile': 'Reset Profile',
    'Gig Worker': 'Gig Worker', Language: 'Language',
    rideshare: 'Rideshare Driver', delivery: 'Delivery Worker',
    freelance: 'Freelancer', contract: 'Contractor',
    // ── Chat overlay ──────────────────────────────────────────────
    'AI Financial Coach': 'AI Financial Coach',
    'Live · Ready to help': 'Live · Ready to help',
    'Ask:': 'Ask:', 'AI is responding…': 'AI is responding…',
    'Ask your coach…': 'Ask your coach…', 'Ask your AI coach': 'Ask your AI coach',
    // ── Dashboard: top banner ─────────────────────────────────────
    'ai_badge': 'AI Analysis · from your bank statements',
    'ai_title': "Here's what we found in your statements",
    'based_on_profile': 'Based on your financial profile',
    'based_on_months': 'Based on {n} months of statements · {from} to {to}',
    // ── Dashboard: stat card labels ───────────────────────────────
    'stat_avg_income': 'Avg monthly income', 'stat_sub_avg_income': '12-month average',
    'stat_avg_spend': 'Avg monthly spend', 'stat_sub_avg_spend': 'All categories',
    'stat_savings': 'Savings balance', 'stat_sub_savings': 'From savings statement',
    'stat_debt': 'Debt payments', 'stat_sub_debt': 'Credit & loans',
    'stat_insurance': 'Insurance',
    'stat_covered': '✓ Covered', 'stat_none': '✗ None',
    'stat_detected': 'Detected in statements', 'stat_not_found': 'Not found — high risk',
    // ── Dashboard: score card ─────────────────────────────────────
    'score_prefix': 'Financial survival score',
    'score_stable': 'Stable', 'score_needs_work': 'Needs work', 'score_critical': 'Critical',
    'score_desc_stable': 'You have a solid base. Keep building your runway and close any coverage gaps.',
    'score_desc_medium': "You're one slow month away from real trouble. Three specific fixes will raise this score significantly.",
    'score_desc_critical': 'Your situation is critical. Immediate action on the items below is essential.',
    'sf_income': 'Income stability', 'sf_tax': 'Tax reserve',
    'sf_savings': 'Savings buffer', 'sf_coverage': 'Coverage gaps',
    // ── Dashboard: survival stats ─────────────────────────────────
    'runway_header': 'If you stopped working today',
    'runway_body': 'Your {savings} in savings would last {weeks} week{s} at your spending level. Goal is 6 months.',
    'worst_header': 'On your worst month',
    'worst_lowest': 'Your lowest month was {income}.',
    'worst_deficit': 'After expenses you run a {amount} deficit — savings drain fast.',
    'worst_surplus': 'After expenses you have {amount} left — a thin cushion.',
    'tax_header': 'Quarterly tax estimate',
    'tax_body': 'Self-employment tax is ~25% of quarterly income. At your average of {income}/mo, you owe ~{tax} every quarter.',
    // ── Dashboard: verdict ────────────────────────────────────────
    'verdict_high_title': "You're heading toward a crisis — but you still have time",
    'verdict_med_title': "You're managing, but one bad month could hurt",
    'verdict_low_title': "You're in a solid position — keep building your buffer",
    'verdict_high_msg': 'Your income swings {pct}% and you have only {weeks} week{s} of savings. {insurance}Start with the actions below.',
    'verdict_high_insurance': 'No insurance means one emergency could wipe everything. ',
    'verdict_med_msg': 'Income volatility is {pct}% and your buffer covers {weeks} weeks. Build toward 90 days of runway to absorb a slow stretch.',
    'verdict_low_msg': 'You have {weeks} weeks of runway and manageable volatility. Keep saving and make sure your insurance coverage is complete.',
    // ── Dashboard: action plan ────────────────────────────────────
    'do_this_now': 'Do this now', 'n_critical': '{n} critical',
    'crisis_advisor_btn': 'Crisis Advisor',
    'act_tax_title': 'Save ${monthly}/mo for your quarterly tax bill',
    'act_tax_body': 'As a gig worker you owe ~${qTax} in self-employment tax every quarter. Open a separate "taxes" savings account and auto-transfer ${monthly} every month starting now.',
    'act_tax_tag': '${qTax} due quarterly', 'tag_critical': 'Critical',
    'act_ins_title': 'Get health insurance — marketplace plans start at $0/mo',
    'act_ins_body': 'You have no health insurance. One ER visit costs $3,000–$8,000 out of pocket. At your income of ${income}/mo you likely qualify for a subsidized ACA plan at healthcare.gov.',
    'tag_ins_cost': '~$0–50/mo', 'tag_score_pts_20': '+20 score pts',
    'act_platform_title': 'Add a backup income platform — 20 minutes to sign up',
    'act_platform_body': '100% of your income comes from one platform. One deactivation = $0 overnight. Adding a backup platform takes 20 minutes and activates in 1–3 days. Protects your full income from a single point of failure.',
    'tag_buffer': 'Adds income buffer', 'tag_score_pts_8': '+8 score pts',
    'act_fund_title': 'Build emergency fund — need ${needed} more for 3-month buffer',
    'act_fund_body': 'You have {days} days of runway. Goal is 90 days (${goal}). Even adding $200/mo consistently will get you there in {months} months.',
    'tag_runway': '{days}d runway', 'tag_high_priority': 'High priority',
  },

  es: {
    Dashboard: 'Tablero', Prepare: 'Preparar', 'Crisis Advisor': 'Asesor de Crisis',
    Spending: 'Gastos', 'Claim Guard': 'Guardia de Reclamos', Settings: 'Configuración',
    Main: 'Principal', Tools: 'Herramientas', Account: 'Cuenta', 'Reset Profile': 'Restablecer',
    'Gig Worker': 'Trabajador Gig', Language: 'Idioma',
    rideshare: 'Conductor de Viajes', delivery: 'Repartidor',
    freelance: 'Freelancer', contract: 'Contratista',
    'AI Financial Coach': 'Coach Financiero IA',
    'Live · Ready to help': 'En vivo · Listo para ayudar',
    'Ask:': 'Preguntar:', 'AI is responding…': 'La IA está respondiendo…',
    'Ask your coach…': 'Pregunta al coach…', 'Ask your AI coach': 'Pregunta al coach IA',
    'ai_badge': 'Análisis IA · de tus extractos bancarios',
    'ai_title': 'Esto es lo que encontramos en tus extractos',
    'based_on_profile': 'Basado en tu perfil financiero',
    'based_on_months': 'Basado en {n} meses de extractos · {from} a {to}',
    'stat_avg_income': 'Ingreso mensual promedio', 'stat_sub_avg_income': 'Promedio de 12 meses',
    'stat_avg_spend': 'Gasto mensual promedio', 'stat_sub_avg_spend': 'Todas las categorías',
    'stat_savings': 'Saldo de ahorros', 'stat_sub_savings': 'Del extracto de ahorros',
    'stat_debt': 'Pagos de deuda', 'stat_sub_debt': 'Crédito y préstamos',
    'stat_insurance': 'Seguro',
    'stat_covered': '✓ Cubierto', 'stat_none': '✗ Ninguno',
    'stat_detected': 'Detectado en extractos', 'stat_not_found': 'No encontrado — alto riesgo',
    'score_prefix': 'Puntaje de supervivencia financiera',
    'score_stable': 'Estable', 'score_needs_work': 'Necesita mejora', 'score_critical': 'Crítico',
    'score_desc_stable': 'Tienes una base sólida. Sigue construyendo tu reserva y cierra las brechas de cobertura.',
    'score_desc_medium': 'Estás a un mes lento de tener problemas reales. Tres correcciones específicas aumentarán este puntaje significativamente.',
    'score_desc_critical': 'Tu situación es crítica. Es esencial actuar de inmediato en los puntos a continuación.',
    'sf_income': 'Estabilidad de ingresos', 'sf_tax': 'Reserva fiscal',
    'sf_savings': 'Colchón de ahorros', 'sf_coverage': 'Brechas de cobertura',
    'runway_header': 'Si dejaras de trabajar hoy',
    'runway_body': 'Tus {savings} en ahorros durarían {weeks} semana{s} a tu nivel de gasto. La meta es 6 meses.',
    'worst_header': 'En tu peor mes',
    'worst_lowest': 'Tu mes más bajo fue {income}.',
    'worst_deficit': 'Después de gastos tienes un déficit de {amount} — los ahorros se agotan rápido.',
    'worst_surplus': 'Después de gastos te quedan {amount} — un colchón delgado.',
    'tax_header': 'Estimación fiscal trimestral',
    'tax_body': 'El impuesto por cuenta propia es ~25% del ingreso trimestral. Con tu promedio de {income}/mes, debes ~{tax} cada trimestre.',
    'verdict_high_title': 'Te diriges hacia una crisis — pero aún tienes tiempo',
    'verdict_med_title': 'Te estás manejando, pero un mal mes podría hacerte daño',
    'verdict_low_title': 'Estás en buena posición — sigue construyendo tu colchón',
    'verdict_high_msg': 'Tus ingresos varían {pct}% y solo tienes {weeks} semana{s} de ahorros. {insurance}Empieza con las acciones a continuación.',
    'verdict_high_insurance': 'Sin seguro, una emergencia podría acabar con todo. ',
    'verdict_med_msg': 'La volatilidad de ingresos es {pct}% y tu reserva cubre {weeks} semanas. Busca llegar a 90 días de reserva para absorber períodos lentos.',
    'verdict_low_msg': 'Tienes {weeks} semanas de reserva y volatilidad manejable. Sigue ahorrando y asegúrate de que tu cobertura de seguro esté completa.',
    'do_this_now': 'Haz esto ahora', 'n_critical': '{n} crítico',
    'crisis_advisor_btn': 'Asesor de Crisis',
    'act_tax_title': 'Ahorra ${monthly}/mes para tu factura fiscal trimestral',
    'act_tax_body': 'Como trabajador independiente debes ~${qTax} en impuestos cada trimestre. Abre una cuenta de ahorros "impuestos" y transfiere automáticamente ${monthly} cada mes.',
    'act_tax_tag': '${qTax} por trimestre', 'tag_critical': 'Crítico',
    'act_ins_title': 'Obtén seguro médico — los planes del mercado empiezan en $0/mes',
    'act_ins_body': 'No tienes seguro médico. Una visita a urgencias cuesta $3,000–$8,000 de tu bolsillo. Con tu ingreso de ${income}/mes probablemente calificas para un plan ACA subsidiado.',
    'tag_ins_cost': '~$0–50/mes', 'tag_score_pts_20': '+20 pts de puntaje',
    'act_platform_title': 'Agrega una plataforma de respaldo — 20 minutos para registrarte',
    'act_platform_body': '100% de tus ingresos vienen de una plataforma. Una desactivación = $0 de la noche a la mañana. Agregar una plataforma de respaldo toma 20 minutos y se activa en 1–3 días.',
    'tag_buffer': 'Agrega colchón de ingresos', 'tag_score_pts_8': '+8 pts de puntaje',
    'act_fund_title': 'Construye fondo de emergencia — necesitas ${needed} más para reserva de 3 meses',
    'act_fund_body': 'Tienes {days} días de reserva. La meta es 90 días (${goal}). Añadir $200/mes consistentemente te llevará allí en {months} meses.',
    'tag_runway': '{days}d de reserva', 'tag_high_priority': 'Alta prioridad',
  },

  zh: {
    Dashboard: '仪表板', Prepare: '准备', 'Crisis Advisor': '危机顾问',
    Spending: '支出', 'Claim Guard': '理赔保护', Settings: '设置',
    Main: '主要', Tools: '工具', Account: '账户', 'Reset Profile': '重置资料',
    'Gig Worker': '零工工人', Language: '语言',
    rideshare: '网约车司机', delivery: '外卖员',
    freelance: '自由职业者', contract: '合同工',
    'AI Financial Coach': 'AI财务教练',
    'Live · Ready to help': '在线 · 随时助您',
    'Ask:': '提问:', 'AI is responding…': 'AI正在回复…',
    'Ask your coach…': '向教练提问…', 'Ask your AI coach': '问AI教练',
    'ai_badge': 'AI分析 · 来自您的银行对账单',
    'ai_title': '我们在您的对账单中发现了什么',
    'based_on_profile': '基于您的财务档案',
    'based_on_months': '基于{n}个月对账单 · {from}至{to}',
    'stat_avg_income': '月均收入', 'stat_sub_avg_income': '12个月平均',
    'stat_avg_spend': '月均支出', 'stat_sub_avg_spend': '所有类别',
    'stat_savings': '储蓄余额', 'stat_sub_savings': '来自储蓄对账单',
    'stat_debt': '债务还款', 'stat_sub_debt': '信用卡及贷款',
    'stat_insurance': '保险',
    'stat_covered': '✓ 已覆盖', 'stat_none': '✗ 无',
    'stat_detected': '在对账单中检测到', 'stat_not_found': '未发现 — 高风险',
    'score_prefix': '财务生存评分',
    'score_stable': '稳定', 'score_needs_work': '需要改善', 'score_critical': '危急',
    'score_desc_stable': '您有良好的基础。继续建立储备并弥补保险缺口。',
    'score_desc_medium': '再有一个收入差的月份就会遇到麻烦。三项具体改进将大幅提升此评分。',
    'score_desc_critical': '您的情况危急，必须立即采取以下行动。',
    'sf_income': '收入稳定性', 'sf_tax': '税务储备',
    'sf_savings': '储蓄缓冲', 'sf_coverage': '保险缺口',
    'runway_header': '如果您今天停止工作',
    'runway_body': '您的{savings}储蓄在当前支出水平下可维持{weeks}周。目标是6个月。',
    'worst_header': '在您最差的月份',
    'worst_lowest': '您收入最低的月份是{income}。',
    'worst_deficit': '扣除支出后您有{amount}的赤字 — 储蓄快速消耗。',
    'worst_surplus': '扣除支出后您还剩{amount} — 缓冲很薄。',
    'tax_header': '季度税款估算',
    'tax_body': '自雇税约为季度收入的25%。按您月均{income}计算，每季度需缴纳约{tax}。',
    'verdict_high_title': '您正走向危机 — 但您仍有时间',
    'verdict_med_title': '您在应对，但一个糟糕的月份可能会造成伤害',
    'verdict_low_title': '您处于稳健状态 — 继续建立缓冲',
    'verdict_high_msg': '您的收入波动{pct}%，储蓄仅够{weeks}周。{insurance}请从以下行动开始。',
    'verdict_high_insurance': '没有保险意味着一次紧急情况可能耗尽一切。 ',
    'verdict_med_msg': '收入波动率为{pct}%，储备可维持{weeks}周。建议达到90天储备以应对淡季。',
    'verdict_low_msg': '您有{weeks}周的储备，波动可控。继续储蓄并确保保险覆盖完整。',
    'do_this_now': '立即行动', 'n_critical': '{n}项关键',
    'crisis_advisor_btn': '危机顾问',
    'act_tax_title': '每月存${monthly}用于季度税款',
    'act_tax_body': '作为零工工人，您每季度需缴纳约${qTax}的自雇税。开设独立的"税务"储蓄账户，每月自动转账${monthly}。',
    'act_tax_tag': '每季度${qTax}', 'tag_critical': '关键',
    'act_ins_title': '购买健康保险 — 市场计划最低$0/月',
    'act_ins_body': '您没有健康保险。一次急诊费用为$3,000–$8,000。以您${income}/月的收入，可能符合ACA补贴计划资格。',
    'tag_ins_cost': '约$0–50/月', 'tag_score_pts_20': '+20分',
    'act_platform_title': '增加备用收入平台 — 注册只需20分钟',
    'act_platform_body': '您100%的收入来自一个平台。一次停用=一夜归零。增加备用平台只需20分钟，1-3天后即可激活。',
    'tag_buffer': '增加收入缓冲', 'tag_score_pts_8': '+8分',
    'act_fund_title': '建立应急基金 — 还需${needed}达到3个月缓冲',
    'act_fund_body': '您有{days}天的储备，目标是90天(${goal})。每月稳定存入$200，{months}个月后即可达到目标。',
    'tag_runway': '{days}天储备', 'tag_high_priority': '高优先级',
  },

  vi: {
    Dashboard: 'Bảng điều khiển', Prepare: 'Chuẩn bị', 'Crisis Advisor': 'Tư vấn khủng hoảng',
    Spending: 'Chi tiêu', 'Claim Guard': 'Bảo vệ khiếu nại', Settings: 'Cài đặt',
    Main: 'Chính', Tools: 'Công cụ', Account: 'Tài khoản', 'Reset Profile': 'Đặt lại hồ sơ',
    'Gig Worker': 'Lao động tự do', Language: 'Ngôn ngữ',
    rideshare: 'Tài xế công nghệ', delivery: 'Nhân viên giao hàng',
    freelance: 'Freelancer', contract: 'Nhà thầu',
    'AI Financial Coach': 'Huấn luyện viên tài chính AI',
    'Live · Ready to help': 'Trực tiếp · Sẵn sàng hỗ trợ',
    'Ask:': 'Hỏi:', 'AI is responding…': 'AI đang phản hồi…',
    'Ask your coach…': 'Hỏi huấn luyện viên…', 'Ask your AI coach': 'Hỏi huấn luyện viên AI',
    'ai_badge': 'Phân tích AI · từ sao kê ngân hàng của bạn',
    'ai_title': 'Đây là những gì chúng tôi tìm thấy trong sao kê của bạn',
    'based_on_profile': 'Dựa trên hồ sơ tài chính của bạn',
    'based_on_months': 'Dựa trên {n} tháng sao kê · {from} đến {to}',
    'stat_avg_income': 'Thu nhập trung bình/tháng', 'stat_sub_avg_income': 'Trung bình 12 tháng',
    'stat_avg_spend': 'Chi tiêu trung bình/tháng', 'stat_sub_avg_spend': 'Tất cả danh mục',
    'stat_savings': 'Số dư tiết kiệm', 'stat_sub_savings': 'Từ sao kê tiết kiệm',
    'stat_debt': 'Thanh toán nợ', 'stat_sub_debt': 'Thẻ tín dụng & vay',
    'stat_insurance': 'Bảo hiểm',
    'stat_covered': '✓ Được bảo hiểm', 'stat_none': '✗ Không có',
    'stat_detected': 'Phát hiện trong sao kê', 'stat_not_found': 'Không tìm thấy — rủi ro cao',
    'score_prefix': 'Điểm tồn tại tài chính',
    'score_stable': 'Ổn định', 'score_needs_work': 'Cần cải thiện', 'score_critical': 'Nguy cấp',
    'score_desc_stable': 'Bạn có nền tảng vững chắc. Tiếp tục xây dựng dự phòng và lấp đầy khoảng trống bảo hiểm.',
    'score_desc_medium': 'Chỉ cần một tháng thu nhập thấp là bạn gặp rắc rối. Ba cải tiến cụ thể sẽ nâng điểm số này đáng kể.',
    'score_desc_critical': 'Tình hình của bạn rất nguy cấp. Hành động ngay lập tức với các mục dưới đây là điều cần thiết.',
    'sf_income': 'Ổn định thu nhập', 'sf_tax': 'Dự phòng thuế',
    'sf_savings': 'Đệm tiết kiệm', 'sf_coverage': 'Khoảng trống bảo hiểm',
    'runway_header': 'Nếu bạn ngừng làm việc hôm nay',
    'runway_body': '{savings} tiết kiệm của bạn sẽ đủ dùng trong {weeks} tuần ở mức chi tiêu hiện tại. Mục tiêu là 6 tháng.',
    'worst_header': 'Vào tháng tệ nhất của bạn',
    'worst_lowest': 'Tháng thu nhập thấp nhất của bạn là {income}.',
    'worst_deficit': 'Sau chi phí bạn thâm hụt {amount} — tiết kiệm cạn kiệt nhanh chóng.',
    'worst_surplus': 'Sau chi phí bạn còn {amount} — một khoản đệm mỏng.',
    'tax_header': 'Ước tính thuế hàng quý',
    'tax_body': 'Thuế tự doanh là ~25% thu nhập hàng quý. Với thu nhập trung bình {income}/tháng, bạn nợ khoảng {tax} mỗi quý.',
    'verdict_high_title': 'Bạn đang tiến đến khủng hoảng — nhưng vẫn còn thời gian',
    'verdict_med_title': 'Bạn đang xoay sở, nhưng một tháng xấu có thể gây hại',
    'verdict_low_title': 'Bạn đang ở vị trí tốt — tiếp tục xây dựng đệm',
    'verdict_high_msg': 'Thu nhập của bạn biến động {pct}% và bạn chỉ có {weeks} tuần tiết kiệm. {insurance}Bắt đầu với các hành động bên dưới.',
    'verdict_high_insurance': 'Không có bảo hiểm nghĩa là một tình huống khẩn cấp có thể xóa sạch tất cả. ',
    'verdict_med_msg': 'Biến động thu nhập là {pct}% và đệm của bạn đủ cho {weeks} tuần. Hướng tới 90 ngày dự phòng để hấp thụ các giai đoạn chậm.',
    'verdict_low_msg': 'Bạn có {weeks} tuần dự phòng và biến động có thể kiểm soát. Tiếp tục tiết kiệm và đảm bảo bảo hiểm đầy đủ.',
    'do_this_now': 'Làm ngay bây giờ', 'n_critical': '{n} quan trọng',
    'crisis_advisor_btn': 'Tư vấn khủng hoảng',
    'act_tax_title': 'Tiết kiệm ${monthly}/tháng cho hóa đơn thuế hàng quý',
    'act_tax_body': 'Là lao động tự do, bạn nợ ~${qTax} thuế tự doanh mỗi quý. Mở tài khoản tiết kiệm "thuế" riêng và tự động chuyển ${monthly} mỗi tháng.',
    'act_tax_tag': '${qTax} mỗi quý', 'tag_critical': 'Quan trọng',
    'act_ins_title': 'Mua bảo hiểm sức khỏe — các gói thị trường từ $0/tháng',
    'act_ins_body': 'Bạn không có bảo hiểm sức khỏe. Một lần cấp cứu tốn $3,000–$8,000. Với thu nhập ${income}/tháng, bạn có thể đủ điều kiện nhận trợ cấp ACA.',
    'tag_ins_cost': '~$0–50/tháng', 'tag_score_pts_20': '+20 điểm',
    'act_platform_title': 'Thêm nền tảng thu nhập dự phòng — 20 phút để đăng ký',
    'act_platform_body': '100% thu nhập của bạn đến từ một nền tảng. Một lần bị vô hiệu hóa = $0 qua đêm. Thêm nền tảng dự phòng chỉ mất 20 phút.',
    'tag_buffer': 'Thêm đệm thu nhập', 'tag_score_pts_8': '+8 điểm',
    'act_fund_title': 'Xây dựng quỹ khẩn cấp — cần thêm ${needed} cho đệm 3 tháng',
    'act_fund_body': 'Bạn có {days} ngày dự phòng. Mục tiêu là 90 ngày (${goal}). Thêm $200/tháng sẽ đưa bạn đến đó trong {months} tháng.',
    'tag_runway': '{days} ngày dự phòng', 'tag_high_priority': 'Ưu tiên cao',
  },

  ar: {
    Dashboard: 'لوحة التحكم', Prepare: 'التحضير', 'Crisis Advisor': 'مستشار الأزمات',
    Spending: 'الإنفاق', 'Claim Guard': 'حماية المطالبات', Settings: 'الإعدادات',
    Main: 'الرئيسية', Tools: 'الأدوات', Account: 'الحساب', 'Reset Profile': 'إعادة تعيين',
    'Gig Worker': 'عامل مستقل', Language: 'اللغة',
    rideshare: 'سائق توصيل', delivery: 'عامل توصيل طلبات',
    freelance: 'مستقل', contract: 'متعاقد',
    'AI Financial Coach': 'مدرب مالي بالذكاء الاصطناعي',
    'Live · Ready to help': 'مباشر · جاهز للمساعدة',
    'Ask:': 'اسأل:', 'AI is responding…': 'الذكاء الاصطناعي يرد…',
    'Ask your coach…': 'اسأل مدربك…', 'Ask your AI coach': 'اسأل مدرب الذكاء الاصطناعي',
    'ai_badge': 'تحليل الذكاء الاصطناعي · من كشوف حسابك البنكي',
    'ai_title': 'هذا ما وجدناه في كشوف حساباتك',
    'based_on_profile': 'بناءً على ملفك المالي',
    'based_on_months': 'بناءً على {n} شهرًا من الكشوف · من {from} إلى {to}',
    'stat_avg_income': 'متوسط الدخل الشهري', 'stat_sub_avg_income': 'متوسط 12 شهرًا',
    'stat_avg_spend': 'متوسط الإنفاق الشهري', 'stat_sub_avg_spend': 'جميع الفئات',
    'stat_savings': 'رصيد المدخرات', 'stat_sub_savings': 'من كشف المدخرات',
    'stat_debt': 'مدفوعات الديون', 'stat_sub_debt': 'بطاقات الائتمان والقروض',
    'stat_insurance': 'التأمين',
    'stat_covered': '✓ مؤمَّن', 'stat_none': '✗ لا يوجد',
    'stat_detected': 'تم اكتشافه في الكشوف', 'stat_not_found': 'غير موجود — مخاطر عالية',
    'score_prefix': 'درجة البقاء المالي',
    'score_stable': 'مستقر', 'score_needs_work': 'يحتاج تحسيناً', 'score_critical': 'حرج',
    'score_desc_stable': 'لديك قاعدة متينة. استمر في بناء احتياطيك وأغلق ثغرات التغطية.',
    'score_desc_medium': 'أنت على بُعد شهر سيئ من مشاكل حقيقية. ثلاثة إصلاحات محددة سترفع هذه الدرجة بشكل ملحوظ.',
    'score_desc_critical': 'وضعك حرج. الإجراء الفوري على العناصر أدناه أمر ضروري.',
    'sf_income': 'استقرار الدخل', 'sf_tax': 'احتياطي الضرائب',
    'sf_savings': 'وسادة المدخرات', 'sf_coverage': 'ثغرات التغطية',
    'runway_header': 'لو توقفت عن العمل اليوم',
    'runway_body': 'مدخراتك البالغة {savings} ستدوم {weeks} أسبوع بمستوى إنفاقك الحالي. الهدف هو 6 أشهر.',
    'worst_header': 'في أسوأ شهر لك',
    'worst_lowest': 'كان أدنى دخل شهري لك هو {income}.',
    'worst_deficit': 'بعد المصاريف يكون لديك عجز قدره {amount} — تتآكل المدخرات بسرعة.',
    'worst_surplus': 'بعد المصاريف يتبقى لديك {amount} — وسادة ضئيلة.',
    'tax_header': 'تقدير الضريبة الفصلية',
    'tax_body': 'ضريبة العمل الحر ~25% من الدخل الفصلي. بمتوسطك البالغ {income}/شهر، تدين بـ~{tax} كل ربع سنة.',
    'verdict_high_title': 'أنت تتجه نحو أزمة — لكن لا يزال لديك وقت',
    'verdict_med_title': 'أنت تتعامل مع الوضع، لكن شهرًا سيئًا قد يضر',
    'verdict_low_title': 'أنت في وضع جيد — استمر في بناء احتياطيك',
    'verdict_high_msg': 'يتذبذب دخلك بنسبة {pct}% ولديك فقط {weeks} أسبوع من المدخرات. {insurance}ابدأ بالإجراءات أدناه.',
    'verdict_high_insurance': 'بدون تأمين، طارئ واحد قد يمحو كل شيء. ',
    'verdict_med_msg': 'تذبذب الدخل {pct}% واحتياطيك يغطي {weeks} أسبوعًا. اهدف إلى 90 يومًا من الاحتياطي لاستيعاب الفترات البطيئة.',
    'verdict_low_msg': 'لديك {weeks} أسبوعًا من الاحتياطي وتذبذب يمكن إدارته. استمر في الادخار وتأكد من اكتمال تغطيتك التأمينية.',
    'do_this_now': 'افعل هذا الآن', 'n_critical': '{n} حرجة',
    'crisis_advisor_btn': 'مستشار الأزمات',
    'act_tax_title': 'ادخر ${monthly}/شهر لفاتورة الضرائب الفصلية',
    'act_tax_body': 'كعامل مستقل تدين بـ~${qTax} في ضريبة العمل الحر كل ربع سنة. افتح حساب توفير "ضرائب" منفصلاً وحوّل ${monthly} تلقائيًا كل شهر.',
    'act_tax_tag': '${qTax} كل ربع سنة', 'tag_critical': 'حرج',
    'act_ins_title': 'احصل على تأمين صحي — الخطط تبدأ من $0/شهر',
    'act_ins_body': 'ليس لديك تأمين صحي. زيارة طوارئ واحدة تكلف $3,000–$8,000. بدخلك ${income}/شهر تؤهلك على الأرجح للحصول على خطة ACA مدعومة.',
    'tag_ins_cost': '~$0–50/شهر', 'tag_score_pts_20': '+20 نقطة',
    'act_platform_title': 'أضف منصة دخل بديلة — 20 دقيقة للتسجيل',
    'act_platform_body': '100% من دخلك يأتي من منصة واحدة. تعطيل واحد = $0 بين عشية وضحاها. إضافة منصة بديلة تستغرق 20 دقيقة وتُفعَّل في 1–3 أيام.',
    'tag_buffer': 'يضيف وسادة دخل', 'tag_score_pts_8': '+8 نقاط',
    'act_fund_title': 'ابنِ صندوق طوارئ — تحتاج ${needed} أكثر لاحتياطي 3 أشهر',
    'act_fund_body': 'لديك {days} يوم من الاحتياطي. الهدف هو 90 يومًا (${goal}). إضافة $200/شهر باستمرار ستوصلك خلال {months} أشهر.',
    'tag_runway': 'احتياطي {days} يوم', 'tag_high_priority': 'أولوية عالية',
  },

  fr: {
    Dashboard: 'Tableau de bord', Prepare: 'Préparer', 'Crisis Advisor': 'Conseiller de crise',
    Spending: 'Dépenses', 'Claim Guard': 'Protection des réclamations', Settings: 'Paramètres',
    Main: 'Principal', Tools: 'Outils', Account: 'Compte', 'Reset Profile': 'Réinitialiser',
    'Gig Worker': 'Travailleur indépendant', Language: 'Langue',
    rideshare: 'Chauffeur VTC', delivery: 'Livreur',
    freelance: 'Freelance', contract: 'Contractuel',
    'AI Financial Coach': 'Coach Financier IA',
    'Live · Ready to help': 'En direct · Prêt à aider',
    'Ask:': 'Demander:', 'AI is responding…': "L'IA répond…",
    'Ask your coach…': 'Demandez au coach…', 'Ask your AI coach': 'Demandez au coach IA',
    'ai_badge': 'Analyse IA · à partir de vos relevés bancaires',
    'ai_title': 'Voici ce que nous avons trouvé dans vos relevés',
    'based_on_profile': 'Basé sur votre profil financier',
    'based_on_months': 'Basé sur {n} mois de relevés · de {from} à {to}',
    'stat_avg_income': 'Revenu mensuel moyen', 'stat_sub_avg_income': 'Moyenne sur 12 mois',
    'stat_avg_spend': 'Dépenses mensuelles moyennes', 'stat_sub_avg_spend': 'Toutes catégories',
    'stat_savings': 'Solde d\'épargne', 'stat_sub_savings': 'Depuis le relevé d\'épargne',
    'stat_debt': 'Paiements de dettes', 'stat_sub_debt': 'Crédits et prêts',
    'stat_insurance': 'Assurance',
    'stat_covered': '✓ Couvert', 'stat_none': '✗ Aucun',
    'stat_detected': 'Détecté dans les relevés', 'stat_not_found': 'Non trouvé — risque élevé',
    'score_prefix': 'Score de survie financière',
    'score_stable': 'Stable', 'score_needs_work': 'À améliorer', 'score_critical': 'Critique',
    'score_desc_stable': 'Vous avez une base solide. Continuez à construire votre réserve et combler les lacunes de couverture.',
    'score_desc_medium': 'Un seul mauvais mois peut vous causer de vrais problèmes. Trois correctifs spécifiques augmenteront ce score significativement.',
    'score_desc_critical': 'Votre situation est critique. Une action immédiate sur les éléments ci-dessous est essentielle.',
    'sf_income': 'Stabilité des revenus', 'sf_tax': 'Réserve fiscale',
    'sf_savings': 'Coussin d\'épargne', 'sf_coverage': 'Lacunes de couverture',
    'runway_header': 'Si vous arrêtiez de travailler aujourd\'hui',
    'runway_body': 'Vos {savings} d\'épargne dureraient {weeks} semaine{s} à votre niveau de dépenses. L\'objectif est 6 mois.',
    'worst_header': 'Lors de votre pire mois',
    'worst_lowest': 'Votre mois de revenu le plus bas était {income}.',
    'worst_deficit': 'Après les dépenses vous avez un déficit de {amount} — l\'épargne se vide vite.',
    'worst_surplus': 'Après les dépenses il vous reste {amount} — un coussin mince.',
    'tax_header': 'Estimation fiscale trimestrielle',
    'tax_body': 'La cotisation d\'indépendant est ~25% du revenu trimestriel. Avec votre moyenne de {income}/mois, vous devez ~{tax} chaque trimestre.',
    'verdict_high_title': 'Vous vous dirigez vers une crise — mais vous avez encore le temps',
    'verdict_med_title': 'Vous vous en sortez, mais un mauvais mois pourrait faire mal',
    'verdict_low_title': 'Vous êtes en bonne position — continuez à construire votre coussin',
    'verdict_high_msg': 'Vos revenus varient de {pct}% et vous n\'avez que {weeks} semaine{s} d\'épargne. {insurance}Commencez par les actions ci-dessous.',
    'verdict_high_insurance': 'Sans assurance, une urgence peut tout effacer. ',
    'verdict_med_msg': 'La volatilité des revenus est de {pct}% et votre réserve couvre {weeks} semaines. Visez 90 jours de réserve pour absorber les périodes creuses.',
    'verdict_low_msg': 'Vous avez {weeks} semaines de réserve et une volatilité gérable. Continuez à épargner et assurez-vous que votre couverture est complète.',
    'do_this_now': 'Faites ceci maintenant', 'n_critical': '{n} critique{s}',
    'crisis_advisor_btn': 'Conseiller de crise',
    'act_tax_title': 'Épargnez ${monthly}/mois pour votre facture fiscale trimestrielle',
    'act_tax_body': 'En tant que travailleur indépendant vous devez ~${qTax} de cotisations chaque trimestre. Ouvrez un compte épargne "impôts" séparé et transférez automatiquement ${monthly} chaque mois.',
    'act_tax_tag': '${qTax} par trimestre', 'tag_critical': 'Critique',
    'act_ins_title': 'Souscrivez une assurance santé — les plans démarrent à 0$/mois',
    'act_ins_body': 'Vous n\'avez pas d\'assurance santé. Une visite aux urgences coûte 3 000–8 000 $. Avec votre revenu de ${income}/mois vous êtes probablement éligible à un plan ACA subventionné.',
    'tag_ins_cost': '~0–50$/mois', 'tag_score_pts_20': '+20 pts',
    'act_platform_title': 'Ajoutez une plateforme de revenus de secours — 20 min pour s\'inscrire',
    'act_platform_body': '100% de vos revenus proviennent d\'une seule plateforme. Une désactivation = 0$ du jour au lendemain. Ajouter une plateforme de secours prend 20 minutes.',
    'tag_buffer': 'Ajoute un coussin de revenus', 'tag_score_pts_8': '+8 pts',
    'act_fund_title': 'Constituez un fonds d\'urgence — besoin de ${needed} de plus pour 3 mois',
    'act_fund_body': 'Vous avez {days} jours de réserve. L\'objectif est 90 jours (${goal}). Même 200$/mois de façon constante vous y amènera en {months} mois.',
    'tag_runway': 'Réserve {days}j', 'tag_high_priority': 'Haute priorité',
  },
};

interface LangCtx {
  lang: LangCode;
  setLang: (c: LangCode) => void;
  t: (key: string) => string;
  geminiLangName: string;
}

const LanguageContext = createContext<LangCtx | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(
    () => (localStorage.getItem('crunch_lang') as LangCode) ?? 'en'
  );

  const setLang = (c: LangCode) => { setLangState(c); localStorage.setItem('crunch_lang', c); };
  const t = (key: string) => UI[lang][key] ?? UI['en'][key] ?? key;
  const geminiLangName = LANGUAGES.find(l => l.code === lang)?.name ?? 'English';

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, geminiLangName }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be within LanguageProvider');
  return ctx;
}
